using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Office.Interop.Visio;

namespace VisioAddIn1
{
    class ConvertedConstants
    {
        Microsoft.Office.Interop.Visio.Application vis = new Application();
        AppDomainManagerInitializationOptions Explicit;
        // TODO: Option Explicit ... Warning!!! not translated
        // Standard Settings for Page Layouts (Supposed to be in millimeters)
        public const int alpsPageLayoutAvenueSizeX = 45;
        public const int alpsPageLayoutAvenueSizeY = 21;
        Publicconst object alpsRoutingStyleForNewMessageConnectors = visLORouteStraight;
        // visLORouteStraight, visLORouteDefault, visLORouteRightAngle
        Publicconst object alpsRoutingStyleForNewSBDTransitions = visLORouteStraight;
        // Paths/Names of Stencils
        Publicconst object alpsSIDStencils = "Abstract PASS SID Visio Shapes v0.6.0.vssm";
        Publicconst object alpsSBDStencils = "Abstract PASS SBD Visio Shapes v0.6.0.vssm";
        Publicconst object alspStencilVersion = "v0.6.0";
        Publicconst object alpsDefaultModelNameSpace = "http://subjective-me.jimdo.com/s-bpm/processmodels/";
        Publicconst object useAdditionalShapesActNConnect = false;
        const object useAdditionalShapesActNConnectCompile = false;
        Publicconst object actNConnectXMLNamespace = "http://www.actnconnect.com/schema/businessactor";
        Publicconst object alpsShapeCategoryModelComponent = "alpsModelComponent";
        Publicconst object alpsShapeCategorySIDComponent = "alpsSIDcomponent";
        Publicconst object alpsShapeCategorySIDconnector = "alpsSIDconnector";
        Publicconst object alpsShapeCategorySIDactor = "alpsSIDactor";
        Publicconst object alpsShapeCategorySIDactorWithSBD = "alpsSIDactorWithSBD";
        Publicconst object alpsShapeCategorySBDComponent = "alpsSBDcomponent";
        Publicconst object alpsShapeCategorySBDState = "alpsSBDstate";
        Publicconst object alpsShapeCategorySBDconnector = "alpsSBDconnector";
        Publicconst object alpsShapeCategorySBDinteractionState = "alpsSBDinteractionState";
        Publicconst object alpsShapeCategorySBDinteractionTransition = "alpsInteractionTransition";
        Publicconst object alpsShapeCategoryAbstractElement = "alpsAbstractPassElement";
        Publicconst object alpsShapeCategoryStandardPassElement = "alpsStandardPassElement";
        Publicconst object ancShapeCategoryActNConnectShape = "actNConnectShape";
        Publicconst object ancShapeCategoryLinkConnector = "actNConnectLinkConnector";
        Publicconst object ancShapeCategoryAdditionalInformationHolder = "actNConnectAdditionalInformationHolder";
        Publicconst object ancShapeCategoryUIElementContainer = "actNConnectUIElementContainer";
        Publicconst object ancShapeCategoryUIElement = "actNConnectUIElement";
        Publicconst object ancShapeCategoryDataAccessDefinition = "actNConnectDataAccessDefinition";
        Publicconst object ancShapeCategoryStateRulesDefinition = "actNConnectStateRulesDefinition";
        Publicconst object ancShapeCategoryActorDataDefinition = "actNConnectActorDataDefinition";
        Publicconst object ancShapeCategoryRulesDefintion = "actNConnectRulesDefinition";
        Publicconst object ancShapeCategoryServiceElementContainer = "actNConnectServiceElementContainer";
        Publicconst object ancShapeCategoryServiceElement = "actNConnectServiceElement";
        Publicconst object ancShapeCategoryUiContainerImagePath = "uiContainerImagePath";
        Publicconst object ancPropertieTypeXmlUIDefinition = "xmlUIDefinition";
        Publicconst object ancPropertieTypeXmlDataDefintion = "xmlDataDefintion";
        Publicconst object ancPropertieTypeXmlDataAccess = "xmlDataAccess";
        Publicconst object ancPropertieTypeXmlRules = "xmlRules";
        Publicconst object ancPropertieTypeXmlMetaData = "xmlMetaData";
        Publicconst object ancPropertieTypeXmlVisibleData = "xmlVisibleData";
        Publicconst object ancPropertieTypeXmlContext = "xmlContext";
        Publicconst object ancPropertieTypeXmlMapping = "xmlMapping";
        Publicconst object ancPropertieTypeXmlService = "xmlService";
        Publicconst object ancPropertieTypeOriginElement = "originElement";
        Publicconst object ancPropertieTypeTargetElement = "targetElement";
        Publicconst object ancPropertieTypeIsDefault = "isDefault";
        Publicconst object ancPropertieTypeIsReceiveDefault = "isReceiveDefault";
        Publicconst object ancPropertieTypeIsServiceDefault = "isServiceDefault";
        Publicconst object ancPropertieTypeUIorServiceList = "uiOrServiceList";
        Publicconst object ancPropertieTypePossibleUIorServiceList = "possibleUIorServiceList";
        Publicconst object ancPropertieTypeFixedActorUUID = "fixedActorUUID";
        Publicconst object ancPropertieTypeIsServiceActor = "isServiceActor";
        Publicconst object ancPropertieTypeServiceType = "serviceType";
        Publicconst object ancPropertieTypeActorVersion = "actorVersion";
        Publicconst object alpsPropertieTypeModelComponentID = "modelComponentID";
        Publicconst object alpsPropertieTypeModelComponentType = "modelComponentType";
        Publicconst object alpsPropertieTypeComment = "modelComponentComment";
        Publicconst object alpsPropertieTypeUIAddress = "uiAddress";
        Publicconst object alpsPropertieTypeDocumentType = "abstractLayeredPASSProcessModel";
        Publicconst object alpsPropertieTypePageType = "pageType";
        Publicconst object alpsPropertieTypePageLayer = "pageLayer";
        Publicconst object alpsPropertieTypeExtendsPropertie = "extends";
        Publicconst object alpsPropertieTypeImplementsPropertie = "implements";
        Publicconst object alpsPropertieTypePageModelURI = "modelURI";
        Publicconst object alpsPropertieTypeSBDLinkedSubjectID = "subjectShapeID";
        Publicconst object alpsPropertieTypeLable = "lable";
        Publicconst object alpsPropertieTypeMessageListSend = "messageListSend";
        Publicconst object alpsPropertieTypeMessageListReceived = "messageListReceive";
        Publicconst object alpsPropertieTypeMultiSubject = "multiSubject";
        Publicconst object alpsPropertieTypeStartSubject = "startSubject";
        Publicconst object alpsPropertieTypeActorsphereDisplayOuterSpehere = "dispalyOuterSphere";
        Publicconst object alpsPropertieTypeLinkedInterfaceResource = "linked_Resource";
        Publicconst object alpsPropertieTypeConnectorErrorDisplayMode = "connectorErrorDisplayMode";
        Publicconst object alpsPropertieTypeBoxCanBeMovedFreely = "boxCanBeMovedFreely";
        Publicconst object alpsPropertieTypeMessageList = "messageList";
        Publicconst object alpsPropertieTypeOriginSubject = "originSubject";
        Publicconst object alpsPropertieTypeTargetSubject = "targetSubject";
        Publicconst object alpsPropertieTypeOriginState = "originState";
        Publicconst object alpsPropertieTypeTargetState = "targetState";
        Publicconst object alpsPropertieTypeReceivingSubject = "receivingSubject";
        Publicconst object alpsPropertieTypeSenderOfMessage = "senderOfMessage";
        Publicconst object alpsPropertieTypeConnectorMessage = "message";
        Publicconst object alpsPropertieTypeConnectorMessagePriority = "messageReceivePriorityNumber";
        Publicconst object alpsPropertieTypeMultiSendLowerBound = "multiSendLowerBound";
        Publicconst object alpsPropertieTypeMultiSendUpperBound = "multiSendUpperBound";
        Publicconst object alpsPropertieTypeMultiReceiveLowerBound = "multiReceiveLowerBound";
        Publicconst object alpsPropertieTypeMultiReceiveUpperBound = "multiReceiveUpperBound";
        Publicconst object alpsPropertieTypeReceiverSenderListForSubject = "receiverSenderListForSubject";
        Publicconst object alpsPropertieTypePossibleMessageList = "possibleMessageList";
        Publicconst object alpsPropertieTypeSendingType = "sendingType";
        Publicconst object alpsPropertieTypeReceiveType = "receiveType";
        Publicconst object alpsPropertieTypeSBDStateIsStartState = "isStartState";
        Publicconst object alpsPropertieTypeSBDStateIsEndState = "isEndState";
        Publicconst object alpsPropertieTypeSBDStateHasRefinement = "hasRefinement";
        Publicconst object alpsPropertieTypeSBDStateInCycle = "inCycle";
        Publicconst object alpsPropertieTypeSBDStateMultiplicityLowerBound = "multiplicityLowerBound";
        Publicconst object alpsPropertieTypeSBDStateMultiplicityUpperBound = "multiplicityUpperBound";
        Publicconst object alpsHyperlinkTypeLinkedSBD = "linkedSBD";
        Publicconst object alpsHyperlinksLinkedSIDPage = "linkedSIDPage";
        Publicconst object alpsPropertieValueSBDPage = "SubjectBehavior";
        Publicconst object alpsPropertieValueSIDPage = "SubjectInteraction";
        Publicconst object alpsShapeCategoryStandardActor = "StandardActor";
        Publicconst object alpsShapeCategoryAbstractActor = "AbstractActor";
        Publicconst object alpsShapeCategoryInterfaceActor = "InterfaceActor";
        Publicconst object alpsShapeCategoryActorExtension = "ActorExtension";
        Publicconst object alpsShapeCategoryActorPlaceHolder = "ActorPlaceHolder";
        Publicconst object alpsShapeCategorySIDMessageConnector = "alpsSIDMessageConnector";
        Publicconst object alpsShapeCategoryStandardMessageConnector = "StandardMessageConnector";
        Publicconst object alpsShapeCategoryAbstractMessageConnector = "AbstractMessageConnector";
        Publicconst object alpsShapeCategoryExclusiveMessageConnector = "ExclusiveMessageConnector";
        Publicconst object alpsShapeCategoryCommunicationRestriction = "CommunicationRestriction";
        Publicconst object alpsShapeCategoryFunctionState = "FunctionState";
        Publicconst object alpsShapeCategorySendState = "SendState";
        Publicconst object alpsShapeCategoryReceiveState = "ReceiveState";
        Publicconst object alpsShapeCategoryInterruptReceiveState = "GuardReceiveState";
        Publicconst object alpsShapeCategoryAbstractFunctionState = "AbstractFunctionState";
        Publicconst object alpsShapeCategoryAbstractReceiveState = "AbstractReceiveState";
        Publicconst object alpsShapeCategoryAbstractSendState = "AbstractSendState";
        Publicconst object alpsShapeCategoryGeneralAbstractState = "GeneralAbstractState";
        Publicconst object alpsShapeCategoryStatePlaceHolder = "StatePlaceHolder";
        Publicconst object alpsShapeCategoryStateExtension = "StateExtension";
        Publicconst object alpsShapeCategoryStandardTransition = "StandardTransition";
        Publicconst object alpsShapeCategoryTriggerTransition = "TriggerTransition";
        Publicconst object alpsShapeCategorySucessionTransition = "SuccessionTranstion";
        Publicconst object alpsShapeCategoryReceiveTransition = "ReceiveTransition";
        Publicconst object alpsShapeCategorySendTransition = "SendTransition";
        Publicconst object alpsShapeCategorySBDStateGroup = "GroupState";
        Publicconst object alpsShapeCategoryUserCancelTransition = "UserCancelTransition";
        Publicconst object alpsShapeCategoryTimeOutTransition = "TimeOutTransition";
        Publicconst object alpsShapeCategoryChecklist = "Checklist";
        Publicconst object alpsShapeCategoryGuardReceive = "GuardReceive";
        Publicconst object alpsSIDMasterStandardActor = "StandardActor";
        Publicconst object alpsSIDMasterStandardMessageConnector = "StandardMessageConnector";
        Publicconst object alpsSIDMasterInterfaceActor = "InterfaceActor";
        Publicconst object alpsSIDMasterAbstractActor = "AbstractActor";
        Publicconst object alpsSIDMasterSubjectPlaceHolder = "ActorPlaceHolder";
        Publicconst object alpsSIDMasterSubjectExtension = "ActorExtension";
        Publicconst object alpsSIDMasterAbstractMessageConnector = "AbstractMessageConnector";
        Publicconst object alpsSIDMasterExclusiveMessageConnector = "ExclusiveMessageConnector";
        Publicconst object alpsSIDMasterCommunicationRestriction = "CommunicationRestriction";
        Publicconst object alpsSBDMasterFunctionState = "FunctionState";
        Publicconst object alpsSBDMasterSendState = "SendState";
        Publicconst object alpsSBDMasterReceiveState = "ReceiveState";
        Publicconst object alpsSBDMasterAbstractFunctionState = "AbstractFunctionState";
        Publicconst object alpsSBDMasterAbstractReceiveState = "AbstractReceiveState";
        Publicconst object alpsSBDMasterAbstractSendState = "AbstractSendState";
        Publicconst object alpsSBDMasterGeneralAbstractState = "GeneralAbstractState";
        Publicconst object alpsSBDMasterPlaceHolder = "StatePlaceHolder";
        Publicconst object alpsSBDMasterStateExtension = "StateExtension";
        Publicconst object alpsSBDMasterStandardTransition = "StandardTransition";
        Publicconst object alpsSBDMasterTriggerTransition = "TriggerTransition";
        Publicconst object alpsSBDMasterSucessionTransition = "SuccessionTranstion";
        Publicconst object alpsSBDMasterReceiveTransition = "ReceiveTransition";
        Publicconst object alpsSBDMasterSendTransition = "SendTransition";
        Publicconst object alpsSBDMasterSBDStateGroup = "GroupState";
        Publicconst object alpsSBDMasterUserCancel = "UserCancelTransition";
        Publicconst object alpsSBDMasterTimeOut = "TimeOutTransition";
        Publicconst object alpsSBDMasterChecklist = "Checklist";
        Publicconst object alpsSBDMasterGuardReceive = "GuardReceive";
        Publicconst object ancMasterUIEContainer = "UIContainer";
        Publicconst object ancMasterUILink = "UILink";
        Publicconst object ancMasterUIElement = "UIElement";
        Publicconst object ancMasterActorDataDefintion = "ActorDataDefintion";
        Publicconst object ancMasterDataAccessDefintion = "DataAccessDefintion";
        Publicconst object ancMasterDataLink = "DataLink";
        Publicconst object ancMasterRulesDefinition = "RulesDefinition";
        Publicconst object ancMasterRuleLink = "RuleLink";
        Publicconst object ancMasterServiceElement = "ServiceElement";
        Publicconst object ancMasterServiceElementContainer = "ServiceElementContainer";
        Publicconst object ancMasterServiceLink = "ServiceLink";
        // ####################
        // Rename Dialog


        public string[] alpsAbstractLables()
        {
            string[,] myString;
            myString[0] = alpsShapeCategoryAbstractFunctionState;
            myString[1] = alpsShapeCategoryAbstractSendState;
            myString[2] = alpsShapeCategoryAbstractReceiveState;
            myString[3] = alpsShapeCategoryGeneralAbstractState;
            myString[4] = alpsShapeCategoryStatePlaceHolder;
            myString[5] = alpsShapeCategoryTriggerTransition;
            myString[6] = alpsShapeCategorySucessionTransition;
            return myString;
        }
    }
}
